### ISSUE TITLE
Webinar with EarthCube Technology and Architecture Committee

### ISSUE THREAD

**Issue by rabernat** [pangeo-data/pangeo-discussion#10]
The Earthcube project coordinator sent me the following request

> Members of the EarthCube community are eager to learn about your new project. The EarthCube Technology and Architecture Committee (TAC) will be hosting a series of webinars this fall to promote the new EarthCube projects. Would you or someone from the team be available to make a 15-20 min presentation (overview of your project) at the next TAC meeting on **Thursday September 28 at 330 PM Central Time**?
>
> I'd also be happy to schedule a webinar for our science committee as well. 
Thanks to let me know. If this date does not work, we could schedule in October (5th or 19th).

The proposed date falls right during my class. Would someone else from the team be willing to take this on? Maybe @jhamman or @chiaral?

**Comment by chiaral** [comment]
Thursday 28th we are in seattle - more over I don't think I can say much about technology and architecture of xarrya/dask.

**Comment by jhamman** [comment]
@rabernat - I'd be happy to give a presentation on the 28th provided I can ask for input from the other team members.

**Comment by jhamman** [comment]
Closing now that the presentation is over. Slides are below:

[EarthCubeTechWebinar.pdf](https://github.com/pangeo-data/pangeo-discussion/files/1342370/EarthCubeTechWebinar.pdf)
