### ISSUE TITLE
Ask for allocation on inactive data-processing clusters

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo-discussion#4]
In the call yesterday people mentioned that some other clusters like Geyser may have large memory nodes that are almost always available.  This cluster resource might be a better fit for us.  Would it be possible to ask for an allocation there as well?  I find myself waiting for quite a while if I ask Cheyenne for more than a couple nodes at a time.

I don't know the costs or politics behind asking for compute time allocations.  Please excuse me if I've asked for something silly.

**Comment by rabernat** [comment]
Our [allocation](https://github.com/pangeo-data/pangeo-discussion/wiki/NCAR-CISL-Computing-Allocation) already includes 5000 hours on [Geyser / Caldera](https://www2.cisl.ucar.edu/resources/computational-systems/geyser-and-caldera). (I'm sure that @jhamman's project you have been using until now also has some time on those clusters.) Let's burn through the 5000 allocated hours first, and then we can ask for more.

Submitting jobs to those clusters should hopefully be very similar to using Cheyenne. There are some docs on running interactive jobs on Geyser / Caldera that should be useful:
https://www2.cisl.ucar.edu/resources/computational-systems/geyser-and-caldera/running-interactive-applications

@jhamman also might have some scripts to get you started there.

**Comment by jhamman** [comment]
@mrocklin and @rabernat - I think its best we stay focused on Cheyenne for the short term. Geyser / Caldera are still using the LSF scheduler from Yellowstone. Using these systems will require developing a new setup that will only be around for another month or so. @davidedelvento can elaborate on how/when the Geyser / Caldera systems will be available from PBS/Cheyenne.

**Comment by davidedelvento** [comment]
Geyser and Caldera will be migrated into the Cheyenne network and will be accessible via Slurm. The sysadmins are working on this already, and they've got it kind-of-working but not easy for users yet.

I agree the best course of action is to focus on Cheyenne for the time being and then move to Geyser/Caldera (whose operating system will probably change too) when available via Slurm. Slurm should not too different from PBSPro as LSF is.

**Comment by mrocklin** [comment]
Sounds like we've reached consensus.  Closing.  Thanks all
