### ISSUE TITLE
Initial blogposts

### ISSUE THREAD

**Issue by mrocklin** [pangeo-data/pangeo-discussion#7]
I'm at a point where I would typically write up a developer blogpost about current work and current issues for Dask + HPC systems.

However I probably don't want to publish such a post until after a general announcement goes out. @rabernat has this happened?  If not then is there anything I can do to accelerate such an announcement?

**Comment by rabernat** [comment]
Matt, you clearly move much quicker than the rest of us! 😉  I'm so pleased that you are making such rapid progress.

Thanks for trying to coordinate your post with the general announcement about the award. I am actively working on this announcement with our media office. We hope to make it early next week. Things have been slowed somewhat by the start of classes this week. (Check out my new course on [Research Computing in Earth Science](https://rabernat.github.io/research_computing/pages/schedule.html)!)

So I am optimistic that you can publish this blog post within one week. I hope that delay doesn't cramp your style too much.

**Comment by mrocklin** [comment]
I suspect that my schedule is just generally more fluid than most.  This
and last week were particularly open.  I'll probably be less available
towards the end of September.

I'll hold off on publishing anything until next week.  I may push up a
draft somewhere.

**Comment by mrocklin** [comment]
Oh, I'm way overcommitted.  I just probably have more flexibility about
which parts of those commitments I focus on and which I neglect.

**Comment by mrocklin** [comment]
Here is a draft of a basic blogpost.  As a disclaimer I'm just pushing something out here and not crafting language.  http://matthewrocklin.com/blog/work/2017/09/06/pangeo-1 .  This is on the internet, but not published in any channel except here.

**Comment by spencerahill** [comment]
>my new course on Research Computing in Earth Science

Nice!  Hope it goes well.  I took a similar class in graduate school, albeit for all scientists not just geoscientists, and it was really valuable.  They still nominally offer it, but it looks like this year it was cancelled: https://registrar.princeton.edu/course-offerings/course_details.xml?courseid=011475&term=1182

All of which is to say, we need more classes like yours :)

**Comment by rabernat** [comment]
> If not then is there anything I can do to accelerate such an announcement?

@mrocklin: Payal Cudia of Anaconda now has the text of the Lamont announcement for her review / edit. If you can get her to respond today, then hopefully we can get the announcement out on Monday.

**Comment by rabernat** [comment]
The news story from the Earth Institute is up:
http://blogs.ei.columbia.edu/2017/09/13/pangeo-project-will-improve-access-to-climate-data/

So go ahead with you blog post!

**Comment by mrocklin** [comment]
@rabernat is the full text of the proposal publicly available anywhere?

**Comment by jhamman** [comment]
@mrocklin -

https://figshare.com/articles/Pangeo_NSF_Earthcube_Proposal/5361094

The awards and a few more details are detailed here: https://groups.google.com/forum/#!topic/pangeo/pFKILby3cuI

**Comment by rabernat** [comment]
Great to see the blog post up!
http://matthewrocklin.com/blog/work/2017/09/18/pangeo-1
